(source melpa)

(depends-on "ag")
(depends-on "evil")
(depends-on "flx-ido")
(depends-on "grizzl")
(depends-on "haml-mode")
(depends-on "haskell-mode")
(depends-on "magit")
(depends-on "markdown-mode")
(depends-on "pallet")
(depends-on "projectile")
(depends-on "ruby-tools")
(depends-on "smartparens")
(depends-on "sublimity")
(depends-on "web-mode")
(depends-on "yasnippet")